import type { DecisionRecord, Ticket } from "@/lib/types";

export const tickets: Ticket[] = [
  {
    id: "TKT-1042",
    orderId: "ORD-88419",
    customerId: "CUS-0284",
    customerName: "Maya Rao",
    subject: "Anniversary gift has not moved in 7 days",
    message:
      "The promised date passed yesterday. I still need the headphones before Saturday; please do not cancel if a replacement can arrive.",
    incident: "DELAYED_DELIVERY",
    urgency: "critical",
    status: "open",
    slaHours: 3,
    orderValue: 8499,
    inventory: 14,
    inactiveDays: 7,
    requestedOutcome: "product",
    priority: 0.94,
    churnRisk: 0.82,
    trackingStatus: "No movement since 10 Jul, Pune hub",
  },
  {
    id: "TKT-1038",
    orderId: "ORD-88271",
    customerId: "CUS-0109",
    customerName: "Arjun Shah",
    subject: "Duplicate charge on card",
    message: "I can see the same ₹12,450 payment twice. Please reverse the duplicate immediately.",
    incident: "DUPLICATE_CHARGE",
    urgency: "high",
    status: "approval",
    slaHours: 6,
    orderValue: 12450,
    inventory: 0,
    inactiveDays: 0,
    requestedOutcome: "refund",
    priority: 0.88,
    churnRisk: 0.76,
    trackingStatus: "Delivered",
  },
  {
    id: "TKT-1034",
    orderId: "ORD-88102",
    customerId: "CUS-0420",
    customerName: "Zoya Khan",
    subject: "Camera lens arrived cracked",
    message:
      "The outer box is crushed and the lens is cracked. I uploaded photos and need a replacement.",
    incident: "DAMAGED_PRODUCT",
    urgency: "high",
    status: "running",
    slaHours: 8,
    orderValue: 28990,
    inventory: 3,
    inactiveDays: 0,
    requestedOutcome: "product",
    priority: 0.9,
    churnRisk: 0.71,
    trackingStatus: "Delivered 16 Jul",
  },
  {
    id: "TKT-1029",
    orderId: "ORD-87981",
    customerId: "CUS-0168",
    customerName: "Kabir Mehta",
    subject: "Courier says address failed again",
    message:
      "This is the third failed attempt even though the address is correct. Please investigate.",
    incident: "DELIVERY_FAILURE",
    urgency: "medium",
    status: "open",
    slaHours: 14,
    orderValue: 3699,
    inventory: 21,
    inactiveDays: 3,
    requestedOutcome: "product",
    priority: 0.63,
    churnRisk: 0.55,
    trackingStatus: "Delivery failed ×3",
  },
  {
    id: "TKT-1021",
    orderId: "ORD-87742",
    customerId: "CUS-0344",
    customerName: "Ishita Sen",
    subject: "Wrong size and colour delivered",
    message: "I ordered navy M and received beige XL. Please replace it.",
    incident: "WRONG_PRODUCT",
    urgency: "medium",
    status: "resolved",
    slaHours: 22,
    orderValue: 2499,
    inventory: 8,
    inactiveDays: 0,
    requestedOutcome: "product",
    priority: 0.58,
    churnRisk: 0.42,
    trackingStatus: "Delivered 15 Jul",
  },
];

export const policies = [
  {
    id: "P-02",
    title: "Delayed Delivery Resolution",
    version: "4.1",
    clause: "§4.2",
    text: "A replacement is permitted after five consecutive inactive tracking days when inventory is available and the customer still wants the product.",
    status: "active",
  },
  {
    id: "P-05",
    title: "Financial Remedies",
    version: "3.7",
    clause: "§2.1",
    text: "Refunds above ₹5,000 require human approval in bounded autonomy mode.",
    status: "active",
  },
  {
    id: "P-08",
    title: "Damaged Goods",
    version: "2.9",
    clause: "§3.3",
    text: "Photo-confirmed damage within seven days qualifies for refund or replacement at customer preference.",
    status: "active",
  },
  {
    id: "P-11",
    title: "Duplicate Payments",
    version: "1.8",
    clause: "§1.2",
    text: "A captured duplicate must be refunded to the original payment method after ledger verification.",
    status: "active",
  },
  {
    id: "P-14",
    title: "Service Recovery Credit",
    version: "2.2",
    clause: "§5.4",
    text: "Up to ₹500 store credit may be issued autonomously for a verified SLA breach.",
    status: "active",
  },
];

export const operationalMetrics = {
  openTickets: 37,
  autonomousResolved: 186,
  pendingApprovals: 6,
  avgResolutionMinutes: 4.8,
  compensationSpend: 12840,
  toolSuccessRate: 99.2,
  verificationRate: 100,
  explainabilityCoverage: 100,
};

export const evaluationScenarios = Array.from({ length: 40 }, (_, index) => ({
  id: `EV-${String(index + 1).padStart(2, "0")}`,
  name: ["Delayed delivery", "Lost shipment", "Damaged item", "Wrong item", "Duplicate charge"][
    index % 5
  ],
  expected: [
    "PRIORITY_REPLACEMENT",
    "COURIER_INVESTIGATION",
    "STANDARD_REPLACEMENT",
    "STANDARD_REPLACEMENT",
    "FULL_REFUND",
  ][index % 5],
  passed: true,
}));

export const storedDecisions: Record<string, DecisionRecord> = {};
